[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/content"
  to = "/.netlify/functions/content"
  status = 200

[[redirects]]
  from = "/api/image"
  to = "/.netlify/functions/image"
  status = 200
